#!/usr/bin/env bash
# Merges sci/devnet/sci-predeploy-allocs.json into a generated L2 genesis.json.
#
# Sibling to apply-sci-allocs.sh (which handles the two precompile-marker addresses
# 0xAAAA..00/01). Run BOTH after `setup-l2` and BEFORE base-client / base-builder
# start. Recommended order:
#
#   bash ~/sci-dev/sci-chain/sci/devnet/apply-sci-allocs.sh         .devnet/l2/configs/genesis.json
#   bash ~/sci-dev/sci-chain/sci/devnet/apply-predeploy-allocs.sh   .devnet/l2/configs/genesis.json
#
# What it does:
# - Backs up genesis.json to genesis.json.pre-predeploy
# - jq-merges every entry in sci-predeploy-allocs.json into .alloc
# - Verifies the 4 predeploy addresses are present with non-empty code, and the
#   AgentCircuitBreaker owner storage slot is seeded.
#
# The static sci-predeploy-allocs.json is regenerated by
# `export-predeploy-allocs.sh` whenever the .sol sources change. Re-run that
# generator + commit the JSON before redeploying.

set -euo pipefail

GENESIS=${1:-}
if [[ -z "$GENESIS" ]]; then
  echo "usage: $0 <path-to-genesis.json>" >&2
  exit 2
fi
if [[ ! -f "$GENESIS" ]]; then
  echo "error: $GENESIS not found" >&2
  exit 2
fi

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ALLOCS="$SCRIPT_DIR/sci-predeploy-allocs.json"
if [[ ! -f "$ALLOCS" ]]; then
  echo "error: $ALLOCS not found. Run export-predeploy-allocs.sh to regenerate it." >&2
  exit 2
fi

cp -p "$GENESIS" "$GENESIS.pre-predeploy"

TMP=$(mktemp)
jq --slurpfile p "$ALLOCS" '.alloc += $p[0]' "$GENESIS" >"$TMP"
mv "$TMP" "$GENESIS"

for addr in \
  0xbbbbbbbb00000000000000000000000000000001 \
  0xbbbbbbbb00000000000000000000000000000002 \
  0xbbbbbbbb00000000000000000000000000000003 \
  0xcccccccc00000000000000000000000000000001; do
  code=$(jq -r --arg a "$addr" '.alloc[$a].code // "MISSING"' "$GENESIS")
  if [[ "$code" == "MISSING" || "$code" == "null" ]]; then
    echo "error: alloc[$addr].code missing after merge" >&2
    exit 3
  fi
  echo "ok: alloc[$addr].code (${#code} chars)"
done

owner_slot=$(jq -r '.alloc["0xbbbbbbbb00000000000000000000000000000003"].storage["0x0000000000000000000000000000000000000000000000000000000000000000"] // "MISSING"' "$GENESIS")
echo "ok: AgentCircuitBreaker._owner slot = $owner_slot"

echo "SCI predeploy allocs merged into $GENESIS (backup at $GENESIS.pre-predeploy)"
