//! Compatibility shim mirroring `tempo_chainspec::hardfork` so ported Tempo keychain
//! source files compile verbatim without identifier renaming.
//!
//! Tempo's `TempoHardfork` is generated by an `alloy_hardforks::hardfork!` macro and
//! carries a large trait surface (`TempoHardforks`, `Display`, `FromStr`, gas-limit
//! lookup, etc.). SCI Chain doesn't need any of that — only the variants and the
//! `is_tX()` query methods that the keychain calls. This file provides exactly that
//! shape so verbatim Tempo source compiles, and re-exports the type as `SciHardfork`
//! for SCI-facing consumers.

pub mod hardfork {
    use revm::primitives::hardfork::SpecId;

    /// Tempo-style hardfork ladder. SCI Chain launches at [`Self::T3`] (full feature
    /// set); `Genesis..T2` exist solely to keep ported test fixtures compiling.
    ///
    /// Re-exported as `SciHardfork` for the SCI-facing public API; both names refer
    /// to the same type.
    #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub enum TempoHardfork {
        /// Pre-feature genesis state. Default for tests; production hardcodes `T3`.
        #[default]
        Genesis,
        /// Tempo T0 equivalent. Enforces basic invariants like non-past expiry.
        T0,
        /// Tempo T1 equivalent. Adds revert-on-invalid-calldata semantics.
        T1,
        /// Tempo T1A equivalent. Reserved.
        T1A,
        /// Tempo T1B equivalent. Reserved.
        T1B,
        /// Tempo T1C equivalent. Reserved.
        T1C,
        /// Tempo T2 equivalent. Enforces tx.origin checks for contract callers.
        T2,
        /// Tempo T3 equivalent. Full feature set (call scoping, periodic limits, etc.).
        T3,
    }

    impl TempoHardfork {
        /// Returns `true` at or after the T0 feature level.
        #[inline]
        pub const fn is_t0(&self) -> bool {
            (*self as u8) >= (Self::T0 as u8)
        }

        /// Returns `true` at or after the T1 feature level.
        #[inline]
        pub const fn is_t1(&self) -> bool {
            (*self as u8) >= (Self::T1 as u8)
        }

        /// Returns `true` at or after the T1C feature level.
        #[inline]
        pub const fn is_t1c(&self) -> bool {
            (*self as u8) >= (Self::T1C as u8)
        }

        /// Returns `true` at or after the T2 feature level.
        #[inline]
        pub const fn is_t2(&self) -> bool {
            (*self as u8) >= (Self::T2 as u8)
        }

        /// Returns `true` at or after the T3 feature level.
        #[inline]
        pub const fn is_t3(&self) -> bool {
            (*self as u8) >= (Self::T3 as u8)
        }
    }

    impl From<TempoHardfork> for SpecId {
        /// SCI Chain uses Ethereum's Prague spec under the hood (Cancun + EIP-7702 etc.).
        /// The SCI-level T-fork is orthogonal to the EVM spec and is consulted directly
        /// by the precompile, not via the EVM spec dispatch.
        fn from(_: TempoHardfork) -> Self {
            Self::PRAGUE
        }
    }

    /// SCI-facing alias for [`TempoHardfork`]. Both names refer to the same type;
    /// use this in SCI-original code, use `TempoHardfork` in verbatim Tempo source.
    pub use TempoHardfork as SciHardfork;
}
